use jdbc;

select * from member;

select * from board;

delete * from board;

create database jsp;

use jsp;

DROP TABLE IF EXISTS CATEGORY, BOARD, ATTACHMENT, MEMBER ,COMPANY ,PRODUCT;
-- ALTER TABLE pro_detail DROP FOREIGN KEY pro_detail_ibfk_1;

CREATE TABLE MEMBER (
  no BIGINT AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(20) UNIQUE,
  pw VARCHAR(200),
  name VARCHAR(20),
  tel VARCHAR(11),
  create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO MEMBER VALUES (NULL, 'm01', '1', '리사', '010', NOW());
INSERT INTO MEMBER VALUES (NULL, 'm02', '2', '주혁', '010', NOW());

CREATE TABLE CATEGORY (
  C_CODE INT PRIMARY KEY,
  C_NAME VARCHAR(30) CHECK (C_NAME IN ('공통', '운동', '등산', '게임', '낚시', '요리', '기타'))
);



INSERT INTO CATEGORY (C_CODE, C_NAME) VALUES(10, '공통');
INSERT INTO CATEGORY (C_CODE, C_NAME) VALUES(20, '운동');
INSERT INTO CATEGORY (C_CODE, C_NAME) VALUES(30, '요리');
INSERT INTO CATEGORY (C_CODE, C_NAME) VALUES(70, '기타');

COMMIT;
SELECT * FROM CATEGORY;
-- DROP TABLE IF EXISTS BOARD ;
CREATE TABLE BOARD (
  NO BIGINT PRIMARY KEY AUTO_INCREMENT,
  CATEGORY_CODE INT,
  TITLE VARCHAR(100),
  CONTENT TEXT NOT NULL,
  WRITER varchar(20) NOT NULL,
  COUNT  INT DEFAULT 0 NOT NULL,
  CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  STATUS CHAR(1) DEFAULT 'Y',
  FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORY(C_CODE),
  FOREIGN KEY (WRITER) REFERENCES MEMBER(ID)
);


INSERT INTO BOARD
( CATEGORY_CODE, TITLE, CONTENT, WRITER)
VALUES( 10, '게시글 1 ', '게시글1 CONTENT 입니다 ', 'm01');

INSERT INTO BOARD
( CATEGORY_CODE, TITLE, CONTENT, WRITER)
VALUES( 10, '게시글 2 ', '게시글2 CONTENT 입니다 ', 'm01');
INSERT INTO BOARD
( CATEGORY_CODE, TITLE, CONTENT, WRITER)
VALUES( 10, '게시글 3 ', '게시글3 CONTENT 입니다 ', 'm02');
INSERT INTO BOARD
( CATEGORY_CODE, TITLE, CONTENT, WRITER)
VALUES( 10, '게시글 4 ', '게시글4 CONTENT 입니다 ', 'm02');
INSERT INTO BOARD
( CATEGORY_CODE, TITLE, CONTENT, WRITER)
VALUES( 10, '게시글 5 ', '게시글5 CONTENT 입니다 ', 'm01');


SELECT * FROM BOARD;




-- DROP TABLE IF EXISTS COMPANY;
CREATE TABLE COMPANY (
  ID VARCHAR(200) PRIMARY KEY,
  NAME VARCHAR(200),
  ADDR VARCHAR(200),
  TEL INT
);
INSERT INTO COMPANY VALUES ('c100', 'GOOD', 'SEOUL', 011);

INSERT INTO COMPANY VALUES ('c200', 'JOA', 'BUSAN', 012);

INSERT INTO COMPANY VALUES ('c300', 'MARIA', 'ULSAN', 013);

INSERT INTO COMPANY VALUES ('c400', 'MY', 'KWANGJU', 014);

COMMIT;

-- DROP TABLE IF EXISTS product;
CREATE TABLE PRODUCT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    CONTENT VARCHAR(500),
    PRICE INT,
    COMPANY_ID VARCHAR(200) NOT NULL,
    IMG VARCHAR(255),
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    CREATED_PERSON VARCHAR (100),
  	MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  	MODIFIED_PERSON VARCHAR (100),
  	STATUS CHAR(1) DEFAULT 'Y',
  	FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)

);



-- DROP TABLE IF EXISTS attachment ;
-- 첨부파일 테이블 생성
CREATE TABLE ATTACHMENT (
  ATTACHMENT_NO BIGINT PRIMARY KEY AUTO_INCREMENT,
  REF_PRODUCT_NO BIGINT NOT NULL,
  ORIGINAL_NAME VARCHAR(255) NOT NULL,
  SAVED_NAME VARCHAR(255) NOT NULL,
  SAVE_PATH VARCHAR(1000) NOT NULL,
  THUMBNAIL_PATH VARCHAR(255),
  STATUS VARCHAR(1) DEFAULT 'Y',
  CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  CREATED_PERSON VARCHAR (100),
  MODIFIED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  MODIFIED_PERSON VARCHAR (100),
  FOREIGN KEY (REF_PRODUCT_NO) REFERENCES PRODUCT(ID)
);

SELECT * FROM attachment ;

select * 
from board
order by no desc;
select * from member;

use jsp;

select a.*, b.id company_id, b.name companyname 
from product a
join company b on a.company_id = b.id;

select * from attachment;
select * from company;
select * from board;
commit;


